import Head from 'next/head';

export default function Login() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>이미지</div>
        <div>
          <p>간편하게 로그인하고</p>
          <p>클라온을 시작해 보세요!</p>
        </div>
        <div>
          <button type="button">카카오 버튼</button>
          <button type="button">구글 버튼</button>
        </div>
      </main>
    </>
  );
}
