name: CD

on:
  push:
    branches: ["deploy"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # 브랜치 체크아웃
      - name: branch checkout
        uses: actions/checkout@v3
      # lightsail 에 브랜치 내용 떨구기
      - name: push to deploy server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "./*"
          target: "/home/${{ secrets.USERNAME }}/claon-admin-web"
          strip_components: 1
      # build 파일 배포하기
      - name: deploy project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/${{ secrets.USERNAME }}/claon-admin-web
            pnpm install
            pnpm build
            pm2 restart claon-admin-web
